### PR TITLE
XmlConfigurator: do longer allow dtd processing across all platforms …

### PR DESCRIPTION
**Pull request by SymbioticKilla**
…(LOG4NET-575)

This patch fixes a security vulnerabiliy reported by Karthik Balasundaram. The security
vulnerability was found in the way how log4net parses xml configuration files where it
allowed to process XML External Entity Processing. An attacker could use this as an
attack vector if he could modify the XML configuration file.

### CODE REVIEW

**Comment by SymbioticKilla** [comment]
I hope it is fine. If not than sorry => close/delete it.
Thanks!

**Comment by jazpearson** [comment]
Would be great to see this merged as this is blocking us,

**Comment by NicholasNoise** [comment]
Is there any way to test this behavior?

**Comment by SymbioticKilla** [comment]
Commit wa merged to master branch.

**Comment by fluffynuts** [comment]
Thanks, this fix is now in master & should be available in release 2.0.10

**Pull request closed without merging**
