### PR TITLE
Move site back where it belongs

### PR DESCRIPTION
**Pull request by fluffynuts**
This is work-in-progress: trying to get the log4net site generation working properly again.

### CODE REVIEW

**Comment by fluffynuts** [comment]
@rgoers I've moved the artifacts back where maven recognises them, but the result I get from running a command like `mvn site:stage -DstagingDirectory=$HOME/log4net` gives me a site where the index is ok, but a lot of the linked pages (eg releases) don't exist. I'm not sure if the problem is environmental or otherwise; since I know nothing about maven (another thing to learn!) I'm not 100% sure about where to start tracking this down, but a quick text-search within the site folder & generated area hasn't been very illuminating. I thought I'd start a PR now so that anyone with more knowledge on the tooling could help.

**Comment by rgoers** [comment]
FWIW, the Apache Logging project generally uses "CTR " (commit - then review). So if you are comfortable with the changes being made you don't need to create a PR. Committers generally only create PRs when they really want a code review because they either a) aren't 100% sure they are doing the right thing or b) want others to be aware of some impact the commit is going to cause.

**Comment by fluffynuts** [comment]
@rgoers I had 2 subsequent commits on the PR (didn't realise that you'd acted on it so quickly!) which restore the release folder in the site area, fixing all the missing artifacts that I found upon trying to build the site. Does CTR imply I should simply commit to master on apache/logging-log4net?

**Comment by rgoers** [comment]
> On Aug 26, 2020, at 8:27 PM, Davyd McColl <notifications@github.com> wrote:
> 
> 
> @rgoers <https://github.com/rgoers> I had 2 subsequent commits on the PR (didn't realise that you'd acted on it so quickly!) which restore the release folder in the site area, fixing all the missing artifacts that I found upon trying to build the site. Does CTR imply I should simply commit to master on apache/logging-log4net?
> 
Yes, unless you specifically want others to review it because you aren’t quite sure if it is the right way to do it, the code will cause breaking changes and you want others opinions, etc. For most things you should just commit to master. We all get commit emails and will see it.  Some of us might look at it and if we have questions we will ask.

Ralph

**Comment by fluffynuts** [comment]
@rgoers cool -- but I can't push to apache/logging-log4net:

```
ERROR: Permission to apache/logging-log4net.git denied to fluffynuts.
```

**Comment by rgoers** [comment]
Your apache userid is davydm. It needs to be linked with your GitHub user. See https://gitbox.apache.org/setup/. Apache Logging doesn't have a guide but many projects do. For example, https://cwiki.apache.org/confluence/display/OPENWHISK/Accessing+Apache+GitHub+as+a+Committer

Ralph

**Comment by fluffynuts** [comment]
@rgoers I've gone through the above:
1. linked my apache id davydm to this github account (fluffynuts)
2. accepted the asf invitiation
3. received mail around team addition
4. gitbox seems to think I should be able to push:
image

however, I still can't push to github.com/apache/logging-log4net:
```
ERROR: Permission to apache/logging-log4net.git denied to fluffynuts.
```

I'm not sure what I'm missing, but I'm assuming I've either missed a step or done something wrong.

**Comment by fluffynuts** [comment]
Thanks @rgoers I've managed to push & I've pushed new site content via svn too; getting a little stuck at point 7 of https://cwiki.apache.org/confluence/display/LOGGING/Managing+the+Logging+Services+Web+Site with respect to getting the site live (and haven't done the 2.x symlink to the new content yet as I'm at a windows machine; need to do it quick on my linux box)

**Comment by cremor** [comment]
I'm not sure if this belongs to the changes made in this PR, but https://logging.apache.org/log4net/ (with is the top Google result if you search for "log4net") currently leads to a directory listing.

**Comment by fluffynuts** [comment]
@cremor thanks for reporting; logging sites are in a bit of a state of upheaval right now (as far as I understand). Good people are On It.

**Comment by rgoers** [comment]
Please try it again.

**Comment by rgoers** [comment]
FWIW, the documentation for publishing the web site is at https://cwiki.apache.org/confluence/display/LOGGING/Managing+the+Git+Hosted+Web+Site. So you would run your build to create the web site and then copy it into the [Log4net site](https://github.com/apache/logging-log4net-site) repo.

**Comment by fluffynuts** [comment]
Thanks for sorting it out @rgoers. I'll try to be better prepared next time.

**Comment by cremor** [comment]
@rgoers Now the link https://logging.apache.org/log4net/ works, but the link which is on https://logging.apache.org, which is https://logging.apache.org/log4net/2.x/index.html (both the button on the main site and in the menu at the top), doesn't work any more 😕

**Comment by rgoers** [comment]
Thanks. Those should be fixed now.

**Comment by rgoers** [comment]
None of this was your fault. All these issues were related to me moving the site from the ASF CMS system to GitHub.

Ralph

**Pull request merged**
