### PR TITLE
(LOG4NET-680) For %thread/%t, use the numeric thread ID for .NET worker pool threads

### PR DESCRIPTION
**Pull request by erikma**
After migrating to .NET 6 the %thread field became useless for threadpool threads. Restore logging of the numeric thread ID for this case.

### CODE REVIEW

**Comment by erikma** [comment]
For https://issues.apache.org/jira/browse/LOG4NET-680

**Comment by zhiweiv** [comment]
Any chance to merge this and release a new version asap?

**Review by fluffynuts — APPROVED** [review]
LGTM

**Comment by fluffynuts** [comment]
@zhiweiv I was spinning up a release not too long ago - there are some other small fixes that I'd like to get out. I just got a little swamped with other stuff in the meantime. I'm on leave as of next week, so, at worst, I can commit to putting focus on this on Monday.

**Pull request merged**
