### PR TITLE
Support converting '.NET TP Worker' to the numeric thread ID on .NET 8+

### PR DESCRIPTION
**Pull request by erikmav**

### CODE REVIEW

**Comment by michal-ciechan** [comment]
Any chance this can be merged, so that we don't have to fork.

**Comment by FreeAndNil** [comment]
@fluffynuts can you take a look?

**Comment by vy** [comment]
@erikmav, @michal-ciechan, @FreeAndNil, log4net is in great need of maintainers. @fluffynuts, the only active maintainer, and whom I believe will soon take care of this PR, can definitely use some help. **Would any of you be willing to step up as a maintainer?** If so, could you share this in an email to [dev@](https://logging.apache.org/support.html#maintainer-discussions), please? I cannot speak for the rest of the PMC, but IMO, we can grant a volunteer the committer rights. Equipped with that, they can merge PRs, commit changes, etc. The release cannot be done by committers; there PMC members are needed for reviewing and performing the release anyway.

**Comment by fluffynuts** [comment]
@michal-ciechan merged - I can't make any guarantees of a release date though, but perhaps after I've finished some other opensource PR I've been working on in the little spare time I have for the last 3 weeks (:

**Comment by poormonfared** [comment]
Hi, when will this fix get released?! It's a really hot fix.
We already had similar issues twice. 1-wrong thread name in updating to.net 6; 2-wrong process name after migrating to.net 7.
Why should we see this again? It would be nice if we carefully tracked our previous issues.

**Comment by fluffynuts** [comment]
Considering my constrained time, and even though @FreeAndNil recently stepped up to be a maintainer, I don't see any time really soon. You can, in the meantime, check out the repo, build, and distribute a dll with your app if it's that important. It's not convenient, I'll admit, but if it's urgent, it's an option.

**Comment by poormonfared** [comment]
@fluffynuts actually, if we replaced ThreadName with our customized property field, then we wouldn't need to replace the library anymore.

**Comment by FreeAndNil** [comment]
@erikmav, @michal-ciechan, @poormonfared we've released https://www.nuget.org/packages/log4net/2.0.16

**Pull request merged**
