### PR TITLE
Extension point for handling new lines in RemoteSysLogAppender added

### PR DESCRIPTION
**Pull request by FreeAndNil**
We would like to write new lines in our log messages as '\n' literally.
To do this, I've extracted the existing logic into a new virtual method.

@fluffynuts Could you please review?

The main code churn is from normalizing the method to tabs instead of spaces.

### CODE REVIEW

**Comment by FreeAndNil** [comment]
@fluffynuts Could you please?

**Comment by fluffynuts** [comment]
Sorry, I haven't really had a gap, and tho I'm off work today, I'm nowhere near a machine for much of the day. Perhaps I'll get a chance a little later 😪

**Comment by FreeAndNil** [comment]
No pressure ;-)
Take your time. When you have the time, please take a look at my other PRs #91 & #92

Thank you very much.

**Review by fluffynuts — APPROVED** [review]
looks fine to me

**Pull request merged**
