### PR TITLE
Fix AdoNetAppender using npgsql once again.

### PR DESCRIPTION
**Pull request by NicholasNoise**
Same bug as #71.
npgsql@4.1.9 (above 4.* in general) completely destroys adonet appender.

3.* fails to prepare command but allows to execute it.
4+ fails to prepare and to execute.

### CODE REVIEW

**Comment by NicholasNoise** [comment]
@fluffynuts 2.0.14 pretty please? :)

**Review by fluffynuts — COMMENTED** [review]
LGTM; I have another small issue I'd like to include in a release, but not sure exactly when I'll get to it; hopefully sooner rather than later.

**Comment by NicholasNoise** [comment]
Thank you!
Patiently waiting for upcoming release

**Comment by dskantz** [comment]
@fluffynuts, great! Ping me in the PR if you want me to try it out on SQL Server before you merge. Well, at least on 2019.

**Comment by fluffynuts** [comment]
> @fluffynuts, great! Ping me in the PR if you want me to try it out on SQL Server before you merge. Well, at least on 2019.

You could try a build from master if you're up for it. At least it could confirm or deny whether it's fixed. If not and you're really motivated, fix & pr 😀

**Pull request merged**
