### PR TITLE
Nullable and modernization part 6

### PR DESCRIPTION
**Pull request by erikmav**
Adjusted nullability on some classes after applying the 3.0 binary to two existing projects that have nullable enabled. Changed nullable warnings to errors.

### CODE REVIEW

**Comment by erikmav** [comment]
For #124

**Review by FreeAndNil — APPROVED** [review]
Thanks a lot.
I will test the API with our libraries.

**Comment by erikmav** [comment]
@FreeAndNil  the ugliest adaptations I had to make with the new binary:
* `Level?` on LoggingEvent and its internal data structure required adding a bunch of null checks, especially where there are comparisons of levels. Lots of these in 2 repos. It would be ideal to make that non-nullable and ensure it's set to some default like `Level.Off` or similar.
* `Repository?` on Logger required adding null checks. Generally speaking this is never null in practice, but I don't see what default to set it to.

**Comment by erikmav** [comment]
@FreeAndNil I just tried setting LoggingEvent.Level to non-nullable and set to Level.All. Problem is that null is converted into different policies by different appenders (Debug, Info, or All) so a blanket All policy does not work. Seems like it needs to be left nullable for back compat.

**Pull request merged**
