### PR TITLE
'(doc)' make the method RollingFileAppender.RollFile() virtual.

### PR DESCRIPTION
**Pull request by qub1n**
I need to post process rolled file by archiver and I can hardly achieve it without making this method virtual.

### CODE REVIEW

**Comment by dpsenner** [comment]
Would it be more appropriate to add an invocation of an emty but virtual PostRollFile method?

**Comment by qub1n** [comment]
Yes following empty method would be sufficient.
protected virtual void OnFileRolled(string filename){}

**Comment by dpsenner** [comment]
I propose to add both oldFile and newFile to the method arguments. Is there a reasoning why the pull request is not based onto develop?

**Comment by qub1n** [comment]
Is there a reasoning why the pull request is not based onto develop?
-> No, it was just the default option on GitHub, I will change it.

OK, please cancel this pull request and I will create a new Pull Request on branch 'develop' with following method signature:

protected virtual void OnFileRolled(string fromFile, string toFile){}

**Comment by qub1n** [comment]
I made new pull request (47) on proper branch, please close it.

**Pull request closed without merging**
