### PR TITLE
Fix net40 client profile

### PR DESCRIPTION
**Pull request by NicholasNoise**
log4net_net40cp

### CODE REVIEW

**Comment by NicholasNoise** [comment]
@fluffynuts

**Comment by cremor** [comment]
Not directly related to this PR, but since you are modifying the preprocessor symbols (constants) here I thought I should mention this:
SDK style projects already define various target framework related constants automatically, see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if#remarks

Some of those are the same as are now manually defined in the log4net.csproj and some are different. This might be confusing for developers who don't check if the constants are defined by the project itself.

But it also seems like migration to the official constants is not that easy. Because with them it seems like the version specific constants are **not** enabled for lower versions when a higher version is built.

**Comment by NicholasNoise** [comment]
> @cremor 
> 
> Some of those are the same as are now manually defined in the log4net.csproj and some are different. This might be confusing for developers who don't check if the constants are defined by the project itself.
> 
> But it also seems like migration to the official constants is not that easy. Because with them it seems like the version specific constants are **not** enabled for lower versions when a higher version is built.

You're right, no other way about it. Build-in features are preferable.
But it seems unnecessary since this project is dormant.

I've spent almost two working day to enable netstandard2.0, so yes, is not easy... until old targets are supported.
Should be much easier without legacy preprocessor symbols like 'NETCF', 'CLIENT_PROFILE' and even 'NET20'

**Comment by fluffynuts** [comment]
LGTM; when I have a moment, I'd like to pull down to my machine & build again to double-check; I'm taking a day off from work tomorrow, so perhaps Thursday (:

**Comment by NicholasNoise** [comment]
@fluffynuts last Thursday or this one? =)

**Comment by fluffynuts** [comment]
Sorry, been a bit mad -- the day off turned into a mission (:

anyway, LGTM, merging.

**Pull request merged**
